## AUTOGRAD: AUTOMATIC DIFFERENTIATION
**Central to all neural networks in PyTorch is the autograd package. **

***torch.Tensor is the central class of the package. If you set its attribute .requires_grad as True, it starts to track all operations on it. When you finish your computation you can call .backward() and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute.***

***To stop a tensor from tracking history, you can call .detach() to detach it from the computation history, and to prevent future computation from being tracked.***

***To prevent tracking history (and using memory), you can also wrap the code block in with torch.no_grad():. This can be particularly helpful when evaluating a model because the model may have trainable parameters with requires_grad=True, but for which we don’t need the gradients.***

In [1]:
import torch

In [33]:
x = torch.ones(2, 2, requires_grad=True) # Create a tensor and set requires_grad=True to track computation with it
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [34]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
# y was created as a result of an operation, so it has a grad_fn.
print(y.grad_fn)

In [35]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [8]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a)
print(a.requires_grad)
a.requires_grad = True
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

tensor([[ 7.1391, -4.2675],
        [ 8.5670,  0.8667]])
False
True


**backward()开始反向传播**

In [36]:
out.backward()

In [37]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [43]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm()<1000:
    y = y * 2
print(y)

tensor([1172.0011, -178.4795, -103.0437], grad_fn=<MulBackward0>)


In [44]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [46]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
