### 导入Pytorch

In [1]:
from __future__ import print_function
import torch

**创建一个5\*3的矩阵，没有初始化**

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.1837e-39, 9.9184e-39, 8.4490e-39],
        [9.6428e-39, 1.1112e-38, 9.5511e-39],
        [1.0102e-38, 1.0286e-38, 1.0194e-38],
        [9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38]])


**创建一个随机初始化的矩阵**

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6316, 0.8792, 0.7275],
        [0.9463, 0.1491, 0.6706],
        [0.2051, 0.4500, 0.6548],
        [0.0562, 0.3557, 0.3042],
        [0.2088, 0.5890, 0.5391]])


**Construct a matrix filled zeros and of dtype long**

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


**直接创建tensor**

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


**根据一个已经存在的Tensor创建一个Tensor**

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 0.0358,  0.5113,  1.0366],
        [ 1.0117,  1.1586,  1.0047],
        [-1.2943,  0.8377, -0.1710],
        [-0.4328,  0.7264, -0.6318],
        [-0.4843,  0.5593, -1.0972]])


In [13]:
x = torch.zeros(4, 3, dtype=torch.double)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [16]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 1.0725, -0.6363, -0.4419],
        [-2.5967, -0.7982, -0.9252],
        [ 1.3693,  1.3424,  0.5030],
        [-0.8700, -0.4287,  0.0123]])

**得到x的大小**

In [17]:
print(x.size())

torch.Size([4, 3])


**运算**

In [19]:
y = torch.rand(4, 3)
print(x+y)

tensor([[ 1.9692, -0.2990, -0.4180],
        [-1.7562, -0.2776, -0.7969],
        [ 1.6660,  2.0264,  1.1397],
        [-0.1374,  0.1387,  0.5514]])


In [20]:
print(torch.add(x,y))

tensor([[ 1.9692, -0.2990, -0.4180],
        [-1.7562, -0.2776, -0.7969],
        [ 1.6660,  2.0264,  1.1397],
        [-0.1374,  0.1387,  0.5514]])


**将计算结果赋给一个Tensor**

In [22]:
result = torch.empty(4, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.9692, -0.2990, -0.4180],
        [-1.7562, -0.2776, -0.7969],
        [ 1.6660,  2.0264,  1.1397],
        [-0.1374,  0.1387,  0.5514]])


**这种方式把x加到y本身上去了，改变了y**

In [23]:
y.add_(x)
print(y)

tensor([[ 1.9692, -0.2990, -0.4180],
        [-1.7562, -0.2776, -0.7969],
        [ 1.6660,  2.0264,  1.1397],
        [-0.1374,  0.1387,  0.5514]])


**Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.**

In [24]:
print(x[:, 1])

tensor([-0.6363, -0.7982,  1.3424, -0.4287])


**改变Tensor的大小用torch.view方法**

In [25]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**If you have a one element tensor, use .item() to get the value as a Python number**

In [26]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6537])
-0.6536864042282104


**Converting a Torch Tensor to a NumPy Array**

In [27]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [28]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [29]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


**Converting NumPy Array to Torch Tensor**

In [30]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [31]:
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**Tensors can be moved onto any device using the .to method. .to方法用来转到不同的设备上，CPU和GPU**

In [32]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!